name: default
nudge:
    _target_: nudges.Default
    # Original data from Callaway et al paper
    data: ${hydra:runtime.cwd}/data/default.csv
    # Wrapper to call the LLM APIs
    api_call: ${general.api_call}
    feature_names: [Rooms, Safety, Job Proximity, School Quality, Low Tax Rate]
    # All the prompts necessary to simulate the original paradigm
    initial_prompt: |
      In this task you will choose a neighborhood. Each neighborhood contains several features with points that you will get if you choose the neighborhood. There are different types of features (A and B in the example below) and they are worth different amounts of points (23 and 7) depending on a user's preferences. You want to select the neighborhood with the most points possible.

      |             Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |---------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      | A (Rooms): 23 points | ?              | ?              | ?              | ?              | ?              |
      | B (Safety): 7 points | ?              | ?              | ?              | ?              | ?              |
      Total accumulated cost: 0 points

      The number of features in each neighborhood varies. To see the value of each feature a neighborhood has, you can reveal the corresponding box.

      |             Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |---------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      | A (Rooms): 23 points | ?              | 4.0            | ?              | ?              | ?              |
      | B (Safety): 7 points | ?              | ?              | ?              | ?              | ?              |
      Total accumulated cost: 2 points

      You may reveal as many or as few of these boxes as you wish. This may help you decide which neighborhood to choose. However, it costs 2 points to reveal a box.

      |             Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |---------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      | A (Rooms): 23 points | ?              | 4.0            | ?              | 5.0            | ?              |
      | B (Safety): 7 points | ?              | ?              | 3.0            | ?              | ?              |
      Total accumulated cost: 6 points

      When you have finished revealing boxes, you can select a neighborhood. In this example, let's imagine that you select Neighborhood 4.

      In this case, you would score 5 on feature A (worth 23 multiplying utility points) and 4 on feature B (worth 7 multiplying utility points), for a total of 143 points. However, because you spent 6 points revealing three boxes, your net utility would be 137 points.

      |             Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |---------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      | A (Rooms): 23 points | ?              | 4.0            | ?              | 5.0            | ?              |
      | B (Safety): 7 points | ?              | ?              | 3.0            | 4.0            | ?              |
      Total accumulated cost: 6 points
      You scored 5.0 on A, and 4.0 on B, totaling 143.0 utility points.
      Total net utility (after lookup costs): 137.0 points.

      Different tasks will have different numbers of neighborhoods and features.

      |                    Features | Neighborhood 1 | Neighborhood 2 |
      |----------------------------:|:---------------|:---------------|
      |      A (Rooms): 3 points    | ?              | ?              |
      |      B (Safety): 6 points   | ?              | ?              |
      | C (Job Proximity): 8 points | ?              | ?              |
      | D (School Quality): 10 pts  | ?              | ?              |
      |   E (Low Tax Rate): 3 pts   | ?              | ?              |
      Total accumulated cost: 0 points

      Let's see the values that would be revealed for all of the boxes on this task. Note that because each box costs 2 points to reveal, revealing all 10 of them would cost 20 points.

      |                    Features | Neighborhood 1 | Neighborhood 2 |
      |----------------------------:|:---------------|:---------------|
      |      A (Rooms): 3 points    | 5.0            | 7.0            |
      |      B (Safety): 6 points   | 4.0            | 8.0            |
      | C (Job Proximity): 8 points | 4.0            | 6.0            |
      | D (School Quality): 10 pts  | 4.0            | 5.0            |
      |   E (Low Tax Rate): 3 pts   | 6.0            | 5.0            |
      Total accumulated cost: 20 points

      The actual values in the boxes can be anywhere from 0 to 10. Also note that different neighborhoods can have different total numbers of points.

      |                    Features | Neighborhood 1 | Neighborhood 2 |
      |----------------------------:|:---------------|:---------------|
      |      A (Rooms): 3 points    | 5.0            | 7.0            |
      |      B (Safety): 6 points   | 4.0            | 8.0            |
      | C (Job Proximity): 8 points | 4.0            | 6.0            |
      | D (School Quality): 10 pts  | 4.0            | 5.0            |
      |   E (Low Tax Rate): 3 pts   | 6.0            | 5.0            |
      Total accumulated cost: 20 points

      The weights of the features will always add up to 30 points. This means that when there are more types of features, the features will be worth less.

      On tasks with two types of features, the feature weights will be worth 15 points on average.

      |             Features | Neighborhood 1 | Neighborhood 2 |
      |---------------------:|:---------------|:---------------|
      | A (Rooms): 6 points  | 5.0            | 7.0            |
      | B (Safety): 24 points | 4.0            | 8.0            |
      Total accumulated cost: 0 points

      And on tasks with five types of features, the feature weights will be worth 6 points on average.

      |             Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |---------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      | A (Rooms): 8 points          | ?              | ?              | ?              | ?              | ?              |
      | B (Safety): 15 points        | ?              | ?              | ?              | ?              | ?              |
      | C (Job Proximity): 4 points  | ?              | ?              | ?              | ?              | ?              |
      | D (School Quality): 2 points | ?              | ?              | ?              | ?              | ?              |
      | E (Low Tax Rate): 1 points   | ?              | ?              | ?              | ?              | ?              |
      Total accumulated cost: 0 points

      On certain tasks, you will have the option of choosing a recommended neighborhood before revealing any boxes.

      The recommended neighborhood is the highest-scoring neighborhood if the feature weights are worth equal numbers of points.

      Do you want to choose neighborhood 3?
      It scores the highest when all feature weights are equally valuable.

      |              Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |----------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      | A (Rooms): 12 points  | ?              | ?              | ?              | ?              | ?              |
      | B (Safety): 18 points | ?              | ?              | ?              | ?              | ?              |
      Total accumulated cost: 0 points

      After choosing a neighborhood, you move on to a new task. With each new round, the number of features in each neighborhood will change. The value of the feature weights will also change.

    supports_integers: ${provider.supports_integers}

    seed: ${general.seed}
