name: highlight
nudge:
    _target_: nudges.Highlight
    # Original data from Callaway et al paper
    data: ${hydra:runtime.cwd}/data/highlight.csv
    # Wrapper to call the LLM APIs
    api_call: ${general.api_call}
    feature_names: [Rooms, Safety, Job Proximity, School Quality, Low Tax Rate]
    # All the prompts necessary to simulate the original paradigm
    initial_prompt: |
      In this task you will see a table like this and you will choose a neighborhood.

      Cost of looking up feature A=3 points, B=1 point, and C=3 points

      |                        Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |--------------------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      |        A (Rooms): 2 points      | ?              | ?              | ?              | ?              | ?              |
      |       B (Safety): 18 points     | ?              | ?              | ?              | ?              | ?              |
      | C (Job Proximity): 10 points    | ?              | ?              | ?              | ?              | ?              |
      Total accumulated cost: 0 points

      Each neighborhood has three types of features weighted differently (2 points for feature A, 18 points for feature B, and 10 points for feature C in this example) depending on a user's preferences. You want to select the neighborhood with the most points possible.

      Cost of looking up feature A=3 points, B=1 point, and C=3 points

      |                        Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |--------------------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      |        A (Rooms): 2 points      | ?              | ?              | ?              | ?              | ?              |
      |       B (Safety): 18 points     | ?              | ?              | ?              | ?              | ?              |
      | C (Job Proximity): 10 points    | ?              | ?              | ?              | ?              | ?              |
      Total accumulated cost: 0 points

      Numbers hidden with a question mark in the boxes show the value of the feature in a neighborhood.

      Cost of looking up feature A=3 points, B=1 point, and C=3 points

      |                        Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |--------------------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      |        A (Rooms): 2 points      | 6.0            | ?              | ?              | ?              | ?              |
      |       B (Safety): 18 points     | ?              | ?              | ?              | ?              | ?              |
      | C (Job Proximity): 10 points    | ?              | ?              | ?              | ?              | ?              |
      Total accumulated cost: 3 points

      Most boxes cost 3 points to reveal, but on certain tasks one feature's boxes will be put on sale and cost only 1 point to reveal. On this problem, feature B is on sale.

      Cost of looking up feature A=3 points, B=1 point, and C=3 points

      |                        Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |--------------------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      |        A (Rooms): 2 points      | 6.0            | ?              | ?              | ?              | ?              |
      |       B (Safety): 18 points     | ?              | ?              | ?              | ?              | ?              |
      | C (Job Proximity): 10 points    | ?              | ?              | ?              | ?              | ?              |
      Total accumulated cost: 3 points

      You can reveal as many or as few boxes as you wish.

      Cost of looking up feature A=3 points, B=1 point, and C=3 points

      |                        Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |--------------------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      |        A (Rooms): 2 points      | 6.0            | ?              | ?              | 5.0            | ?              |
      |       B (Safety): 18 points     | 7.0            | ?              | ?              | ?              | ?              |
      | C (Job Proximity): 10 points    | ?              | 7.0            | ?              | ?              | ?              |
      Total accumulated cost: 10 points

      Whenever you're ready, you can choose a neighborhood. Let's imagine that you choose Neighborhood 1.

      Cost of looking up feature A=3 points, B=1 point, and C=3 points

      |                        Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |--------------------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      |        A (Rooms): 2 points      | 6.0            | ?              | ?              | 5.0            | ?              |
      |       B (Safety): 18 points     | 7.0            | ?              | ?              | ?              | ?              |
      | C (Job Proximity): 10 points    | 4.0            | 7.0            | ?              | ?              | ?              |
      Total accumulated cost: 10 points
      You scored 6.0 on A, 7.0 on B, and 4.0 on C, totaling 178.0 utility points.
      Total net utility (after lookup costs): 168.0 points.

      If so, you would score 6 on feature A (worth 2 multiplying utility points), 7 on feature B (18 multiplying utility points), and 4 on C (10 multiplying utility points), for a total of 178 points. However, because you spent 10 points revealing, you would earn 168 points on this trial.

      Cost of looking up feature A=3 points, B=1 point, and C=3 points

      |                        Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |--------------------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      |        A (Rooms): 2 points      | 6.0            | ?              | ?              | 5.0            | ?              |
      |       B (Safety): 18 points     | 7.0            | ?              | ?              | ?              | ?              |
      | C (Job Proximity): 10 points    | 4.0            | 7.0            | ?              | ?              | ?              |
      Total accumulated cost: 10 points

      The value of each feature will vary between problems. Note that on certain problems, no feature will be put on sale and all boxes will cost 3 points to reveal.

      Cost of looking up feature A=3 points, B=3 points, and C=3 points

      |                        Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |--------------------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      |        A (Rooms): 7 points      | ?              | ?              | ?              | ?              | ?              |
      |       B (Safety): 19 points     | ?              | ?              | ?              | ?              | ?              |
      | C (Job Proximity): 4 points     | ?              | ?              | ?              | ?              | ?              |
      Total accumulated cost: 0 points

      Let's see the values that you'd see if you revealed all of the boxes on this task. The actual values in the boxes can be anywhere from 0 to 10, and you can't have negative values (that would be a bummer!)

      Cost of looking up feature A=3 points, B=3 points, and C=3 points

      |                        Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |--------------------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      |        A (Rooms): 7 points      | 3.0            | 9.0            | 9.0            | 5.0            | 4.0            |
      |       B (Safety): 19 points     | 5.0            | 5.0            | 2.0            | 4.0            | 4.0            |
      | C (Job Proximity): 4 points     | 4.0            | 5.0            | 1.0            | 6.0            | 4.0            |
      Total accumulated cost: 45 points

    supports_integers: ${provider.supports_integers}

    seed: ${general.seed}
