name: suggestion
nudge:
    _target_: nudges.Suggestion
    # Original data from Callaway et al paper
    data: ${hydra:runtime.cwd}/data/suggestion.csv
    # Wrapper to call the LLM APIs
    api_call: ${general.api_call}
    feature_names: [Rooms, Safety, Job Proximity, School Quality, Low Tax Rate]
    # All the prompts necessary to simulate the original paradigm
    initial_prompt: |
      In this task you will see a table like this and you will choose a neighborhood.

      |              Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |----------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      | A (Rooms): 20 points  | ?              | ?              | ?              | ?              | ?              |
      | B (Safety): 10 points | ?              | ?              | ?              | ?              | ?              |
      Total accumulated cost: 0 points

      Each neighborhood has some features (A and B below), and each feature is weighted depending on a user's preferences. You want to select the neighborhood with the most points possible.

      |              Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |----------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      | A (Rooms): 20 points  | ?              | ?              | ?              | ?              | ?              |
      | B (Safety): 10 points | ?              | ?              | ?              | ?              | ?              |
      Total accumulated cost: 0 points

      To see the values of the features a neighborhood has, you can reveal the corresponding box. Here, you can see that Neighborhood 2 has 4 Rooms (A), which are weighted 20 points.

      |              Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |----------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      | A (Rooms): 20 points  | ?              | 4.0            | ?              | ?              | ?              |
      | B (Safety): 10 points | ?              | ?              | ?              | ?              | ?              |
      Total accumulated cost: 2 points

      You may reveal as many or as few boxes as you wish. However, each box costs 2 points.

      |              Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |----------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      | A (Rooms): 20 points  | ?              | 4.0            | ?              | 2.0            | ?              |
      | B (Safety): 10 points | ?              | ?              | 5.0            | ?              | ?              |
      Total accumulated cost: 6 points

      When you're ready, you can choose a neighborhood. In this example, let's imagine that you choose Neighborhood 3. In this case, you would score 6 on A (worth 20 multiplying utility points) and 5 on B (worth 10 multiplying utility points), for a total of 170 points. However, because you spent 6 points revealing three boxes, your net utility on this task would be 164 points.

      |              Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |----------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      | A (Rooms): 20 points  | ?              | 4.0            | 6.0            | 2.0            | ?              |
      | B (Safety): 10 points | ?              | ?              | 5.0            | ?              | ?              |
      Total accumulated cost: 6 points
      You scored 6.0 on A, and 5.0 on B, totaling 170.0 utility points.
      Total net utility (after lookup costs): 164.0 points.

      On some tasks, there will be five types of features in each neighborhood.

      |                       Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |--------------------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      |         A (Rooms): 3 points    | ?              | ?              | ?              | ?              | ?              |
      |         B (Safety): 1 points   | ?              | ?              | ?              | ?              | ?              |
      | C (Job Proximity): 6 points    | ?              | ?              | ?              | ?              | ?              |
      | D (School Quality): 16 points  | ?              | ?              | ?              | ?              | ?              |
      |    E (Low Tax Rate): 4 points  | ?              | ?              | ?              | ?              | ?              |
      Total accumulated cost: 0 points

      Let's see the values if you revealed all of the boxes. The actual values in the boxes can be anywhere from 0 to 10, and you can't have negative values (that would be a bummer!)

      |                       Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |--------------------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      |         A (Rooms): 3 points    | 4.0            | 5.0            | 6.0            | 4.0            | 7.0            |
      |         B (Safety): 1 points   | 5.0            | 4.0            | 4.0            | 3.0            | 5.0            |
      | C (Job Proximity): 6 points    | 2.0            | 4.0            | 5.0            | 5.0            | 4.0            |
      | D (School Quality): 16 points  | 5.0            | 6.0            | 4.0            | 7.0            | 7.0            |
      |    E (Low Tax Rate): 4 points  | 4.0            | 4.0            | 6.0            | 3.0            | 5.0            |
      Total accumulated cost: 50 points

      On certain tasks, we will highlight one of the neighborhoods and reveal the value of one box.

      Consider neighborhood 5 - it has a B score of 6.0!

      |              Features | Neighborhood 1 | Neighborhood 2 | Neighborhood 3 | Neighborhood 4 | Neighborhood 5 |
      |----------------------:|:---------------|:---------------|:---------------|:---------------|:---------------|
      | A (Rooms): 12 points  | ?              | ?              | ?              | ?              | ?              |
      | B (Safety): 18 points | ?              | ?              | ?              | ?              | 6.0            |
      Total accumulated cost: 0 points

    supports_integers: ${provider.supports_integers}

    seed: ${general.seed}
